//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajudai.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chamado
    {
        public int idChamado { get; set; }
        public int idCliente { get; set; }
        public int idProduto { get; set; }
        public Nullable<int> idFuncionario { get; set; }
        public Nullable<System.DateTime> dtAbertura { get; set; }
        public string Tipo { get; set; }
        public string Descricao_PosicionamentoCliente { get; set; }
        public string Prioridade { get; set; }
        public Nullable<System.DateTime> dtAtendimento { get; set; }
        public string PosicionamentoFuncionario { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> dtSolucao { get; set; }
        public string Solucao { get; set; }
        public string Avaliacao { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
